### ISSUE TITLE
How to run cc-metric-store as a systemd service

### ISSUE THREAD

**Issue by Autumn-Roy** [ClusterCockpit/cc-metric-store#15]
By the setup, cc-metric-store and cc-metric-collector can run by command line. But as a part of ClusterCockpit, I want to run it as a service.
I saw the file `scripts/cc-metric-store.service`, but there is a parameter `EnvironmentFile` confused me. I don't know which file can I sign here.
The same situation happened when I setup cc-metric-collector.

**Comment by TomTheBear** [comment]
The packages copy `scripts/cc-metric-X.config` to `/etc/default/cc-metric-X`. This file is picked up by the service file to get basic settings.

**Comment by Autumn-Roy** [comment]
Thank you for answering.
