### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by iamlouk** [ClusterCockpit/cc-metric-store#6]
This application acts both as a server (via its HTTP API for the ClusterCockpit MetricDataRepositories) and as a client (to the NATS.io server). Both of these communication channels can be secured via JWTs.

NATS restricts JWTs ([See here](https://docs.nats.io/nats-server/configuration/securing_nats/jwt#json-web-tokens)) to the `Ed25519` algorithm.

The cc-metric-store will need to know the public key so that it can verify incoming requests via the HTTP API. Knowing the private key is not needed if the cc-metric-store is provided with a valid JWT signed by someone else (e.g. ClusterCockpit, if it can provide JWTs that conform to the restrictions NATS puts on JWTs).

**Comment by moebiusband73** [comment]
JWT currently has optional authentication via user password.
This should be uniformly JWT tokens

**Comment by moebiusband73** [comment]
Changed to now available NATS credentials in Commit 2d510b289013a6865ad6442566fcf6f4b4e999c5
